import type { Metadata } from "next";
import { Montserrat } from "next/font/google";

import "./globals.css";

import NavBar from "@/components/NavBar";

const font = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "A La Mama",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${font.className} antialiased`}
            >
                <div className="flex flex-col w-screen h-screen">
                    <NavBar />
                    <main className="h-full max-h-full overflow-y-auto">
                        {children}
                    </main>
                </div>
            </body>
        </html>
    );
}
